# Nome do Workflow: Descreve o que o workflow faz.
name: Generate Datas

# Controla quando o workflow será executado.
on:
  schedule:
    # Executa a cada 12 horas.
    # A expressão cron '* */12 * * *' significa:
    # - '*' (minuto): qualquer minuto (0-59)
    # - '*/12' (hora): a cada 12 horas (0, 12)
    # - '*' (dia do mês): qualquer dia (1-31)
    # - '*' (mês): qualquer mês (1-12)
    # - '*' (dia da semana): qualquer dia (0-6, onde 0 é Domingo)
    - cron: "* */12 * * *"
  # Permite que o workflow seja executado manualmente a partir da aba Actions no GitHub.
  workflow_dispatch:

permissions:
  contents: write

# Define os jobs que serão executados no workflow.
jobs:
  # Nome do job. Pode ser qualquer nome descritivo.
  build:
    # Nome que será exibido na UI do GitHub para este job.
    name: Jobs to update datas
    # Especifica o tipo de runner (máquina virtual) onde o job será executado.
    # 'ubuntu-latest' usa a versão estável mais recente do Ubuntu.
    runs-on: ubuntu-latest
    # Define a sequência de passos que compõem o job.
    steps:
      # Passo 1: Gerar a animação da "cobra" das contribuições do GitHub.
      # Utiliza a action 'Platane/snk@master'.
      - name: Generate Snake Animation
        uses: Platane/snk@master
        # 'id' é usado para referenciar os outputs deste passo em passos subsequentes.
        id: snake-gif
        with:
          # Nome de utilizador do GitHub para buscar as contribuições.
          # Deverá ser alterado para o seu nome de utilizador ou o desejado.
          github_user_name: DanyloDuma
          # Caminho onde o ficheiro SVG da animação será guardado.
          # 'dist/' é um diretório comum para artefactos de build.
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Poderia adicionar mais opções aqui, como:
          # gif_out_path: dist/github-contribution-grid-snake.gif # Para gerar também um GIF

      # Passo 2: Fazer deploy dos ficheiros gerados (o SVG da cobra) para o GitHub Pages.
      # Utiliza a action 'crazy-max/ghaction-github-pages@v2.1.3'.
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # O branch para onde os ficheiros serão enviados.
          # Se este branch não existir, será criado.
          target_branch: output
          # O diretório que contém os ficheiros a serem publicados.
          # Corresponde ao 'svg_out_path' do passo anterior (dentro do diretório 'dist').
          build_dir: dist
        env:
          # Token de acesso do GitHub, necessário para fazer push para o repositório.
          # ${{ secrets.GITHUB_TOKEN }} é um token gerado automaticamente pelo GitHub Actions
          # com permissões limitadas ao repositório onde o workflow está a ser executado.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
