name: Генерація даних про активність

on:
  schedule:
    # Запускати кожні 12 годин
    - cron: "0 */12 * * *"
  # Дозволити ручний запуск
  workflow_dispatch:

permissions:
  contents: write  # Дозвіл на запис

jobs:
  generate_stats:
    name: Оновлення статистики
    runs-on: ubuntu-latest
    
    steps:
      # Крок 1: Генерація анімації змії
      - name: Згенерувати анімацію змії
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: xaxsd  # Ваш нікнейм
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Додаткові параметри:
          color: "blue"           # Колір змії
          size: 600               # Розмір зображення
          show_other_days: false  # Показувати тільки ваші дні

      # Крок 2: Генерація статистики
      - name: Згенерувати статистику
        uses: anuraghazra/github-readme-stats@main
        with:
          filename: stats.svg
          path: dist/

      # Крок 3: Завантаження результатів
      - name: Завантажити результати
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output    # Гілка для зберігання
          build_dir: dist         # Папка з файлами
          keep_files: true        # Зберігати попередні файли
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
